### ISSUE TITLE
`make supported` on CircleCI failing

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite-content-packs#10]

**Comment by iCHAIT** [comment]
#

**Comment by benjaoming** [comment]
Possibly (in case Circle doesn't support it), move the project to Travis and follow these instructions to add the API keys that we don't want in the public repo.

https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables
http://stackoverflow.com/questions/9338428/using-secret-api-keys-on-travis-ci

**Comment by aronasorman** [comment]
Stale. Let's reopen if we see any of this. Either way, this is superseded by the Kolibri ecosystem's sushi chefs.
