### ISSUE TITLE
Subtitles disabled on English content pack

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite-content-packs#55]
Not sure about the reasoning for this, should we release 0.17 with a "known issue" that all the English subtitles are missing?

@mrpau-eduard can you comment on the decision to disable it?

https://github.com/learningequality/ka-lite-content-packs/blob/master/contentpacks/__main__.py#L15

https://github.com/learningequality/ka-lite-content-packs/blob/master/Makefile#L3

**Comment by mrpau-eduard** [comment]
I am not sure if we should release  0.17 that all the English subtitles are missing. 
If it is a big issue then can we release another English language pack with subtitles? I can build one if you want me to create another `en` language pack with subtitles. 

I think @aronasorman is the right person to ask about this issue.

**Comment by benjaoming** [comment]
@mrpau-eduard it would be great if you can start a build with subtitles? That way, we can also figure out if it's disabled because of a technical issue.

**Comment by mrpau-eduard** [comment]
Yeah, I will the English language pack with subtitles. Will update you when it is done.

**Comment by mrpau-eduard** [comment]
Done uploading the `en` language pack with subs.
Please grab it here. https://drive.google.com/open?id=0B-E59G3J_sXma1ZfZFdJZ0dMTlE


@radinamatic can you test this `en` language pack with subs.

**Comment by radinamatic** [comment]
@mrpau-eduard There's still something fishy with the English subs: I'm seeing them in OSX but not in Windows with this newest `en` contentpack. 😞 

Tried several times, just to be sure... First of all, it's confusing that after the basic installation there seems to be more than 7000 subtitles, but once you install the `en` contentpack, it says `0 Subtitles`:

#### Before: 
1. Win 8.1
![virtualbox_ie11 - win8 1_12_01_2017_13_36_20](https://cloud.githubusercontent.com/assets/1457929/21891636/f09ff7e2-d8d3-11e6-988f-342df680e7ba.png)

2. OSX
![virtualbox_sierra_12_01_2017_14_06_25](https://cloud.githubusercontent.com/assets/1457929/21891749/6eaa5bfa-d8d4-11e6-8364-1130ba8fad1e.png)

#### After:

3. Win 8.1
![virtualbox_ie11 - win8 1_12_01_2017_14_12_34](https://cloud.githubusercontent.com/assets/1457929/21891080/46c3726e-d8d1-11e6-89eb-5905fbf0255e.png)

4. OSX
![virtualbox_sierra_12_01_2017_14_07_45](https://cloud.githubusercontent.com/assets/1457929/21890957/ac2880c8-d8d0-11e6-818a-208dd664c30c.png)


But the bigger issue is that on PC there's still nothing in `C:\Users\IEUser\.kalite\httpsrv\static\srt\en\subtitles` folder even after the installation of this newest `en` contentpack (see image 3. above), while on macOS Sierra there are 7209 subs in the `\virtual\.kalite\httpsrv\static\srt\en\subtitles` folder:

![virtualbox_sierra_12_01_2017_14_36_57](https://cloud.githubusercontent.com/assets/1457929/21891951/71e6bb28-d8d5-11e6-9429-4013d2226715.png)

Confirming now where do we stand in Ubuntu...

**Comment by radinamatic** [comment]
English subs not present on Ubuntu either:

![virtualbox_ubuntu 16 10_12_01_2017_15_00_57](https://cloud.githubusercontent.com/assets/1457929/21892647/1a62d15e-d8d8-11e6-8c0f-425a48da9f18.png)

**Comment by radinamatic** [comment]
![virtualbox_ubuntu 16 10_12_01_2017_15_07_06](https://cloud.githubusercontent.com/assets/1457929/21892853/09853ca4-d8d9-11e6-9f6e-064f8ba90cdc.png)

Spanish ones are there, but not all... Missing almost all from the `/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/` topic, and they used to be available for sure at some point in the past, but now I can't find them even on KA site, so nothing we can do there,  I guess.

For dubbed Spanish videos KA offers only the YT auto-generated subs that [suck big time](https://es.khanacademy.org/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/v/counting-with-small-numbers)... 😭

**Comment by benjaoming** [comment]
@radinamatic - the new English content pack with subtitles isn't part of `all_metadata.json` which might be the component that still tells you "0 subtitles".

Also, when you use an installer, it probably comes bundled with an English content pack without subtitles.

I'm going to put it on Pantry now and make it available for 0.17 testing...

**Comment by mrpau-eduard** [comment]
Hi @radinamatic can you test this newly built English language pack with subs.
https://drive.google.com/open?id=0B-E59G3J_sXmcmtBUHR0NGZVWXM
I check the `metadata.json` and the content of the language pack. The subtitles are there.
```
{
  "beta": false,
  "code": "en",
  "language_pack_version": 1,
  "name": "English",
  "native_name": "English",
  "percent_translated": 0,
  "software_version": "0.16",
  "subtitle_count": 7864,
  "topic_tree_translated": 0,
  "video_count": 8785
}
```

**Comment by radinamatic** [comment]
Now we are talking... 👍 

Windows:

![virtualbox_windows 7_17_01_2017_12_53_14](https://cloud.githubusercontent.com/assets/1457929/22019534/484dcfda-dcb4-11e6-976e-4dc34a00b1c4.png)

![virtualbox_windows 7_17_01_2017_12_54_53](https://cloud.githubusercontent.com/assets/1457929/22019540/504962ee-dcb4-11e6-875d-3b51b88e5a6a.png)

**Comment by benjaoming** [comment]
I think we can close this already..

The results are in, the new content pack*) works :)

*) Will be released with 0.17

**Comment by radinamatic** [comment]
Thanks @benjaoming! 👍 

I would have closed it myself, but somebody should first grant me those creds for this new repo... 😊 
(cc @aronasorman)

**Comment by benjaoming** [comment]
@radinamatic oh that's silly, you've been added to the "KA Lite Installer" and "KA lite dev" teams!

**Comment by radinamatic** [comment]
@benjaoming Much obliged! ❤️
