### ISSUE TITLE
Approve translation from crowdin is not reflected on the contentpack translation percentage

### ISSUE THREAD

**Issue by mrpau-eduard** [learningequality/ka-lite-content-packs#61]
#### Issue
In [Crowdin](https://crowdin.com/project/ka-lite/pt-PT#) it say's 100% translated for `pt-PT` but when we build the `pt-PT` we will have 88% translated.

#### Findings
The issue is we are comparing the filtered data from the Catalog to the `.po` files directly. There is discrepancy since the Catalog data is refine/filtered, then the `.po` files data are raw.
To test the data discrepancy I convert each data to `json` files and compare it.

You will find the line of code that calculate the translation percentage here:
https://github.com/learningequality/ka-lite-content-packs/blob/master/contentpacks/utils.py#L79

So if we get the percentage we will have:
```
trans_count:(944) all_strings_count:(1074) compute_translated:(87.89571694599627)
```
/cc @benjaoming @cpauya @radinamatic @aronasorman

**Comment by mrpau-eduard** [comment]
Will write a validator for the`msgid` so it will ensure that there is a equivalent `msgid` to the `po` files before calculating the translation percentage.

**Comment by benjaoming** [comment]
@mrpau-eduard great, thanks for finding the explanation!

Can you use the CrowdIn API instead of doing our own calculations?

https://support.crowdin.com/api/status/
