### ISSUE TITLE
Possibly unwrapped and therefore not translated strings 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite-content-packs#71]
# System info
Version: 0.17.1 with latest ES contentpack
OS: Xubuntu 16.04
Browser: Chrome

# Description
Testing the [newest ES contentpack](https://drive.google.com/open?id=0B-E59G3J_sXmazlqUHljaDVTcTQ), and still finding many strings in English, even though Spanish on Crowdin is 100% translated.

![xubuntu start running - oracle vm virtualbox_354](https://user-images.githubusercontent.com/1457929/28194875-59a27ae6-6847-11e7-8e25-7153957e1c5d.png)

Possibilities:

1. PO files from Crowdin are not built into the contentpack.
2. There are strings that are unwrapped/hardcoded, don't get into Crowdin, and are therefore not translated.

This last option seems possible since I searched for several of the above in the files on Crowdin, and could not find them (`Manage` & `Teach` in the main menu, for example).

We've been dragging this for a while now, and we should fix it before the 0.17.2 release.

**Comment by mrpau-eugene** [comment]
@radinamatic Even with the content pack that was released together with `0.17.1` had a similar issue with this. I think that this is possibly related with this [issue](https://github.com/learningequality/ka-lite/issues/5477).

**Comment by radinamatic** [comment]
I agree, it's probably the same problem. We need to do a search and for those strings, export to Crowdin and translate that asap.

**Comment by radinamatic** [comment]
I can do the translation on Crowdin no problem, let me know if I can help otherwise to find those strings... :slightly_smiling_face:

**Comment by radinamatic** [comment]
@mrpau-eugene @mrpau-eduard I installed `0.17.2-rc2`, updated to the latest `en` contentpack, and installed the latest `es` contentpack on top. Nothing much have changed, there are still many UI elements which strings display in English:

![ubuntu3 start running - oracle vm virtualbox_359](https://user-images.githubusercontent.com/1457929/28351400-dec79600-6c4f-11e7-8417-92eda54d485d.png)

Only the names of the topic in the coach report table might actually be a different bug, since those items are present and localized in the Spanish topic tree:

![ubuntu3 start running - oracle vm virtualbox_360](https://user-images.githubusercontent.com/1457929/28351472-64c7b60e-6c50-11e7-8028-43af67e3539c.png)

**Comment by mrpau-eugene** [comment]
@radinamatic Could you check the crowdin and see if those words are translated?

I checked and compared the contentpacks used in 0.17.x and 0.16.x.

0.16.x es contentpack contains

![image](https://user-images.githubusercontent.com/27984604/28351763-6cc0fc4c-6c84-11e7-8562-65c93a803af5.png)

while 0.17.x doesn't have `Manage` in the list

![image](https://user-images.githubusercontent.com/27984604/28351778-89875b0a-6c84-11e7-8d3f-de084cf1b2df.png)

**Comment by radinamatic** [comment]
@mrpau-eugene @mrpau-eduard I agree and I noted that in my original report: Crowdin does not seem to include a lot of those strings. 

So we need to re-generate or extract translatable strings and update the PO file on Crowdin, so they can be translated. Just ping me when that is ready, and I'll finish it for Spanish asap.

**Comment by benjaoming** [comment]
@radinamatic 

You can read about the cause of the issue in https://github.com/learningequality/ka-lite/issues/5477

Underlying causes are:

 1. Messages were generated and uploaded without verification of stats
 1. Untransparent "IGNORE_PATTERNS" was left unmaintained in a python file when project layout was changed (fixed)
 1. Complicated method for generated strings through a central server git with a git submodule (fixed)
 1. Tests didn't insist that this was an actual issue early enough

Let's just say we've all learned something! :)

Great report btw, really sorry this should take so long to figure out.. I wasn't familiar with the way we generated the sources for CrowdIn before now.
