### ISSUE TITLE
Content packs have a hard-coded "language_pack_version: 1"

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite-content-packs#74]
I suggest replacing it with a date stamp, for instance `20170819`.

This way, we won't have to manage any version numbers - which is nice.

I'll fix current .zips on pantry so they don't have to be re-released.

**Comment by benjaoming** [comment]
@mrpau-dev can you guys look into this?

**Comment by mrpau-eugene** [comment]
sure @benjaoming! will look on this

**Comment by benjaoming** [comment]
Fixed in #75
