### ISSUE TITLE
KA Lite substitles 0.16.9 under Linux Ubuntu

### ISSUE THREAD

**Issue by JMNB** [learningequality/ka-lite-content-packs#76]
We have a problem with the English sub-titles in KA-lite version 0.16.9. Although we have downloaded the language pack, and we indicate that we want to see the sub-titles,they are not displayed.

For various reasons we cannot upgrade KA-Lite to version 0.17. 

We run KA-lite on a Linux server, Ubuntu 16.04.3 LTS.

**Comment by mrpau-eugene** [comment]
Hi @JMNB 

Thank you for posting and sorry for the late reply.

May I ask how long have you been using KA-Lite and those various reasons why you can't upgrade to `0.17`

I tried the following to find out whether it's a KA-Lite version issue or a content pack issue:

* Install 0.16.9 with its bundled content pack
* install 0.17.0 with its bundled content pack
* Install 0.16.9 with 0.17.x content pack

Here is what I noticed:

On `0.17.x` installers, it copies the subtitles to `~/.kalite/content/srt/{lang_code}/subtitles/`.
On `0.16.9` installer, it copies the subtitles to `~/.kalite/httpsrv/static/srt/{lang_code}/subtitles/` but when you open the said folder, you won't see any subtitle files `(*.vtt)`

@benjaoming perhaps you have any ideas about this?

**Comment by benjaoming** [comment]
@mrpau-eugene I can confirm that there are no subtitle files in assessment items for 0.16.9. I think *maybe* we had an understanding that the English content pack shouldn't contain subtitles in 0.16 -- a misunderstanding of course. But I think we excluded the subtitles in the English content pack, together with certain dubbed language content packs where the subtitles were translations of a different audio track (not captions).

**Comment by benjaoming** [comment]
@JMNB 0.17 had updates to make English subtitles display by default. I think you should update if you can :)

What are the challenges?

**Comment by JMNB** [comment]
Dear Benjamin and Eugene, 

Thank you for your answer and let’s explain the background for our question:

Last three years we’ve been working with a high school in Addis Ababa, Ethiopia, to introduce e-learning.
 
This high school is part of an organization called Selam Children’s Village. This organization, founded 30 years ago by Mrs. Tsehay Roeschli, to take care of orphans and destitute community children to improve their lives and holistically develop as self-sufficient citizens, http://www.selamchildrenvillage.org <http://www.selamchildrenvillage.org/>.

Our approach has been to create summaries of the Ethiopian  text books for biology, chemistry, mathematics, physics, and history, geography.
The summaries we linked to graphics, animations, exercises and video tutorials, making it an integral part of it by adding links.

We looked for high -quality video lectures off-line available under a Creative Commons-no-commercial license and found the Khan Academy. KA-lite has become our prime source for Mathematics and Science.

Students and teachers at the Selam High School have now access to world class material, integrated into the Ethiopian curriculum.

The quality of the materials also has been recognized by the Ethiopian government, i.e., the Education Bureau of Addis Ababa, and they requested us to support them in introducing the e-learning at governmental high schools, starting in Addis Ababa.
We hope this opportunity will eventually make it available to Ethiopian students in Addis Ababa, and maybe also the rural areas - where there are more than 60 students in one class, and schools organize the classes in multiple shifts, because a shortage of teachers and class rooms.


Last year we installed a first version on the e-Learning summaries on RaspberryPI’s  using KA-lite 0.16, with help of Benjamin; each subject has its own RaspberryPI. The students are using the subtitles, because that give them a better understanding of the material. Their textbooks are in English as well.

For maintainability and extended use possibilities we transferred the RaspberryPI e-Learning to a Linux-Ubuntu webserver.  

We also installed KA-lite 0.17, but we found out that the database tree for the video lectures and exercises was modified, meaning for us that we had to modify partly and test all (1500 +) links in the e-Learning material to KA-lite. We considered this option, but taking in mind that Debian and Ubuntu are not that different we decided to continue using KA-lite 0.16. 

Later we found out that there was a problem with the subtitles  after re-installation and re-testing, we contacted you asking for help and support. 

We hope you will understand our considerations and challenges, but we also want to thank you for the work done making the Ka-lite video lectures and exercises available offline.
 
Kind regards, 
 
Wim and Julia Nolles

**Comment by mrpau-eugene** [comment]
@JMNB

I would like to suggest to use the `0.17.x` installers. Content packs do not rely on the version of KA-Lite you are using.

So if ever you install `0.17.3` installer, you can remove the contents by deleting the `~/.kalite` folder.

And then run `kalite manage setup`
```
Generating a new secret key file /Users/home/.kalite/secretkey.txt...


   _   __  ___    _     _ _
  | | / / / _ \  | |   (_) |
  | |/ / / /_\ \ | |    _| |_ ___
  |    \ |  _  | | |   | | __/ _ \
  | |\  \| | | | | |___| | ||  __/
  \_| \_/\_| |_/ \_____/_|\__\___|

https://learningequality.org/ka-lite/

         version 0.17.3

--------------------------------------------------------------------------------
This script will configure the database and prepare it for use.
--------------------------------------------------------------------------------

Press [enter] to continue...
Please choose a username and password for the admin account on this device.
    You must remember this login information, as you will need
    to enter it to administer this installation of KA Lite.
Username (leave blank to use 'user'): a
Password:
Password (again):
Please enter a hostname for this server (or, press Enter to use 'user.local'): 
Please enter a one-line description for this server (or, press Enter to leave blank): 
Copying database file from /Users/user/Desktop/ka-lite/kalite/database/templates/data.sqlite to /Users/user/.kalite/database/data.sqlite
Copying /Users/user/Desktop/ka-lite/kalite/database/templates/content_items/content_khan_en.sqlite to /Users/user/.kalite/database/content_khan_en.sqlite

In order to access many of the available exercises, you need to load a content pack for the latest version.
If you have an Internet connection, you can download the needed file. Warning: this may take a long time!

If you have already downloaded the content pack, you can specify the location of the file in the next step.
Otherwise, we will download it from http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip.
Do you wish to download and install the content pack now? (yes or no) no
Do you have a local copy of the content pack already downloaded that you want to install? (yes or no) yes
Please enter the filename of the content pack you have downloaded (): /Users/user/Downloads/en.zip
[WARNING] [2017-11-20 09:01:29,365] kalite: No en_icu.js file found in locale_path /Users/user/.kalite/locale
[WARNING] [2017-11-20 09:01:29,365] kalite: No en_icu.js file found in locale_path /Users/user/.kalite/locale
[INFO] [2017-11-20 09:01:29,366] kalite: Writing i18nized js file to /Users/user/.kalite/content/locale/js/i18n/en.js
[INFO] [2017-11-20 09:02:07,067] kalite: Annotating content for language: en, channel: khan

This may take several minutes depending on system resources...
[INFO] [2017-11-20 09:02:11,803] kalite: Annotation complete for language: en, channel: khan
Generating 2048-bit RSA encryption key (may take a few minutes; please wait)...
Done!
Device 'gg' ('gg') has been successfully initialized.
Superuser created successfully.
Copying static media...
Annotating availability of all content, checking for content in this directory: /Users/user/.kalite/content
[INFO] [2017-11-20 09:02:18,076] kalite: Annotating content for language: en, channel: khan

This may take several minutes depending on system resources...
[INFO] [2017-11-20 09:02:21,181] kalite: Annotation complete for language: en, channel: khan

CONGRATULATIONS! You've finished setting up the KA Lite server software.
```

Take note of these steps:

> If you have already downloaded the content pack, you can specify the location of the file in the next step.
Otherwise, we will download it from http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip.
Do you wish to download and install the content pack now? (yes or no) **no**
Do you have a local copy of the content pack already downloaded that you want to install? (yes or no) **yes**
Please enter the filename of the content pack you have downloaded (): **/Users/user/Downloads/en.zip**


`0.16.x` english content pack can be found [here.](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/en.zip):

**Comment by benjaoming** [comment]
What @mrpau-eugene seems to make sense in your situation @JMNB -- try installing KA Lite 0.17 without the content pack bundled (use either the `ka-lite-raspberry-pi` or `ka-lite` package for Debian, but \*not\* the `ka-lite-bundle`).

>  We also installed KA-lite 0.17, but we found out that the database tree for the video lectures and exercises was modified, meaning for us that we had to modify partly and test all (1500 +) links in the e-Learning material to KA-lite. We considered this option, but taking in mind that Debian and Ubuntu are not that different we decided to continue using KA-lite 0.16.

Our tests show that you can use KA Lite 0.17 with the content pack from 0.16. Links and videos will thus remain the same. Just upgrade the software and leave the contents as they are. Thanks @mrpau-eugene for the research here!

**Small note:** After installing, you should see that some very long-lasting content annotation takes place, this is an issue that we are aware of, basically KA Lite scans for all of the videos in the database, even though the database hasn't changed.

**Comment by JMNB** [comment]
Dear Eugene and Benjamin, 

 

Thank you for your answer and instruction how to install KALite version 0.17 without changing the database structure.

 

I tried as you proposed, but was not successful:

 

After:

 

Copying database file from /Users/user/Desktop/ka-lite/kalite/database/templates/data.sqlite to /Users/user/.kalite/database/data.sqlite
Copying /Users/user/Desktop/ka-lite/kalite/database/templates/content_items/content_khan_en.sqlite to /Users/user/.kalite/database/content_khan_en.sqlite

 

This part was not displayed:

 

In order to access many of the available exercises, you need to load a content pack for the latest version.
If you have an Internet connection, you can download the needed file. Warning: this may take a long time!
 
If you have already downloaded the content pack, you can specify the location of the file in the next step.
Otherwise, we will download it from http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip.
Do you wish to download and install the content pack now? (yes or no) no
Do you have a local copy of the content pack already downloaded that you want to install? (yes or no) yes
Please enter the filename of the content pack you have downloaded (): /Users/user/Downloads/en.zip

 

Until the warning was displayed: 

 

[warning] kalite: No en_icu.js file found in locale_path /home/selam/.kalite/locale

[warning] kalite: No en_icu.js file found in locale_path /home/selam/.kalite/locale

[info]kalite: Writing i18nizedjs file to home/selam/kalite/content/locale/js/i18n/en.js

[info]kalite: Annotating content for language: en, channel: khan

…

 

What went wrong? On another machine we have still 0.16.9 KALite running under Ubuntu, so perhaps we have to copy some files from that one.

We have also a directory with all video lectures as well as a directory with of vtt files.

 

Another possibility is to install the server from scratch with first Ubuntu, followed by kalite 0.16.9, Debian 0.17.3 ?

 

Thank a lot beforehand, kind regards,

 

Wim and Julia Nolles

 

Van: Benjamin Bach [mailto:notifications@github.com] 
Verzonden: 20 November 2017 13:13
Aan: learningequality/ka-lite-content-packs <ka-lite-content-packs@noreply.github.com>
CC: JMNB <julia.nolles@me.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [learningequality/ka-lite-content-packs] KA Lite substitles 0.16.9 under Linux Ubuntu (#76)

 

What @mrpau-eugene <https://github.com/mrpau-eugene>  seems to make sense in your situation @JMNB <https://github.com/jmnb>  -- try installing KA Lite 0.17 without the content pack bundled (use either the ka-lite-raspberry-pi or ka-lite package for Debian, but *not* the ka-lite-bundle).

We also installed KA-lite 0.17, but we found out that the database tree for the video lectures and exercises was modified, meaning for us that we had to modify partly and test all (1500 +) links in the e-Learning material to KA-lite. We considered this option, but taking in mind that Debian and Ubuntu are not that different we decided to continue using KA-lite 0.16.

Our tests show that you can use KA Lite 0.17 with the content pack from 0.16. Links and videos will thus remain the same. Just upgrade the software and leave the contents as they are. Thanks @mrpau-eugene <https://github.com/mrpau-eugene>  for the research here!

Small note: After installing, you should see that some very long-lasting content annotation takes place, this is an issue that we are aware of, basically KA Lite scans for all of the videos in the database, even though the database hasn't changed.

**Comment by JMNB** [comment]
Dear Eugene and Benjamin, 

 

Meanwhile We tried the second option: Install Ubuntu from scratch, followed by KAlite 0.16.9 and Debian-RaspberryPI 0.17.3 according to the instructions on the Learning equality website.

But the KAlite installer ran into problems telling that he was missing something on nginx . . We tried to install it, but were not successful.

 

Have a nice evening, Wim and Julia

 

Van: Julia Nolles [mailto:julia.nolles@me.com] 
Verzonden: 20 November 2017 16:10
Aan: 'learningequality/ka-lite-content-packs' <reply@reply.github.com>; 'learningequality/ka-lite-content-packs' <ka-lite-content-packs@noreply.github.com>
CC: 'Mention' <mention@noreply.github.com>
Onderwerp: RE: [learningequality/ka-lite-content-packs] KA Lite substitles 0.16.9 under Linux Ubuntu (#76)

 

Dear Eugene and Benjamin, 

 

Thank you for your answer and instruction how to install KALite version 0.17 without changing the database structure.

 

I tried as you proposed, but was not successful:

 

After:

 

Copying database file from /Users/user/Desktop/ka-lite/kalite/database/templates/data.sqlite to /Users/user/.kalite/database/data.sqlite
Copying /Users/user/Desktop/ka-lite/kalite/database/templates/content_items/content_khan_en.sqlite to /Users/user/.kalite/database/content_khan_en.sqlite

 

This part was not displayed:

 

In order to access many of the available exercises, you need to load a content pack for the latest version.
If you have an Internet connection, you can download the needed file. Warning: this may take a long time!
 
If you have already downloaded the content pack, you can specify the location of the file in the next step.
Otherwise, we will download it from http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip.
Do you wish to download and install the content pack now? (yes or no) no
Do you have a local copy of the content pack already downloaded that you want to install? (yes or no) yes
Please enter the filename of the content pack you have downloaded (): /Users/user/Downloads/en.zip

 

Until the warning was displayed: 

 

[warning] kalite: No en_icu.js file found in locale_path /home/selam/.kalite/locale

[warning] kalite: No en_icu.js file found in locale_path /home/selam/.kalite/locale

[info]kalite: Writing i18nizedjs file to home/selam/kalite/content/locale/js/i18n/en.js

[info]kalite: Annotating content for language: en, channel: khan

…

 

What went wrong? On another machine we have still 0.16.9 KALite running under Ubuntu, so perhaps we have to copy some files from that one.

We have also a directory with all video lectures as well as a directory with of vtt files.

 

Another possibility is to install the server from scratch with first Ubuntu, followed by kalite 0.16.9, Debian 0.17.3 ?

 

Thank a lot beforehand, kind regards,

 

Wim and Julia Nolles

 

Van: Benjamin Bach [mailto:notifications@github.com] 
Verzonden: 20 November 2017 13:13
Aan: learningequality/ka-lite-content-packs <ka-lite-content-packs@noreply.github.com <mailto:ka-lite-content-packs@noreply.github.com> >
CC: JMNB <julia.nolles@me.com <mailto:julia.nolles@me.com> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Onderwerp: Re: [learningequality/ka-lite-content-packs] KA Lite substitles 0.16.9 under Linux Ubuntu (#76)

 

What @mrpau-eugene <https://github.com/mrpau-eugene>  seems to make sense in your situation @JMNB <https://github.com/jmnb>  -- try installing KA Lite 0.17 without the content pack bundled (use either the ka-lite-raspberry-pi or ka-lite package for Debian, but *not* the ka-lite-bundle).

We also installed KA-lite 0.17, but we found out that the database tree for the video lectures and exercises was modified, meaning for us that we had to modify partly and test all (1500 +) links in the e-Learning material to KA-lite. We considered this option, but taking in mind that Debian and Ubuntu are not that different we decided to continue using KA-lite 0.16.

Our tests show that you can use KA Lite 0.17 with the content pack from 0.16. Links and videos will thus remain the same. Just upgrade the software and leave the contents as they are. Thanks @mrpau-eugene <https://github.com/mrpau-eugene>  for the research here!

Small note: After installing, you should see that some very long-lasting content annotation takes place, this is an issue that we are aware of, basically KA Lite scans for all of the videos in the database, even though the database hasn't changed.

**Comment by mrpau-eugene** [comment]
@JMNB 

May we know the reason why you did this?

```
Copying database file from /Users/user/Desktop/ka-lite/kalite/database/templates/data.sqlite to /Users/user/.kalite/database/data.sqlite
Copying /Users/user/Desktop/ka-lite/kalite/database/templates/content_items/content_khan_en.sqlite to /Users/user/.kalite/database/content_khan_en.sqlite
```

Btw, if you are on a Raspberry PI, you are supposed to download this: http://pantry.learningequality.org/downloads/ka-lite/0.17/installers/debian/ka-lite-raspberry-pi_0.17.3-0ubuntu1_all.deb

as suggested by @benjaoming

And then download the 0.16.9 content packs here: http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/en.zip

I haven't tested it yet since I don't have a raspberry pi with me but most likely you will have a similar output from the one I posted since it will prompt you the location of the content packs

**Comment by JMNB** [comment]
Sorry Eugene for the misunderstanding:

These messages were displayed on the screen as you mentioned. We will download the content pack for 0.16.9 in the ~/Downloads directory and will do another try today.

We are working in a lIinux- Ubuntu platform, although in the past we used a RaspberryPI and Benjamin helped us.

Thank again, 

Wim and Julia

**Comment by JMNB** [comment]
Dear Eugene and Benjamin, 

Yes, we were successful today and managed to install KALite 0.17.3 with the 0.16.9 database and subtitles thanks to you commands and support.

We only see a message when in the home-page of KALite:

Dear Admin, please log in and upgrade the following languages as soon as possible: English

Please find attached document describing what we did.

Thank you also on behalf of the Ethiopian students, so they have now the opportunity to listen and read in English what is told in the video lectures. Perhaps some video lectures will be subtitles by Amharic, their own language. We will keep you informed.

Kind regards, 

Wim and Julia Nolles

**Comment by benjaoming** [comment]
Hi @JMNB 

I hope you have managed to resolve this, if not please let us know.

Sorry that we didn't get back -- I think we lack the attached document. You cannot attach documents via email. But you can attach something if you use the comment field on Github:

https://github.com/learningequality/ka-lite-content-packs/issues/76

Please consider using our main support forum here: http://community.learningequality.org/

Best,
Ben

**Comment by JMNB** [comment]
Benjamin, 

Yes, we were successful and were able to repeat the installation several times.

For others, please follow these instructions (only tested in Ubuntu 16.04 lts):
1. sudo apt-get install python-pip
2. cd Downloads
3. Download ka-lite-bundle_0.16.9-0ubuntu3_all.deb 
4. sudo dpkg -i ka-lite-bundle_0.16.9-0ubuntu3_all.deb
5. Answer the questions as asked
6. If finished: start KAlite and create the admin account and login as admin; register device
7. Reboot
8. Download the static version of KAlite 0.17: http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip.
9. cd Downloads
10. sudo tar -xf ka-lite-static-0.17.3.tar.gz
11. Go to the ka-lite-static-0.17.3 - directory: cd ka-lite-static-0.17.3
12. sudo python setup.py install
13. Return to the Downloads-directory: cd ..
14. Download the subtitles: http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip and make sure that the file is stored in the Downloads-directory
15. Disconnect from internet
16. kalite manage setup
17. Enter 'yes' to the question:
     Keep database file and upgrade to KA Lite version 0.17.3 (yes or no)
18. Enter '/home/selam/Downloads/en.zip' on the question:
     Please enter the filename of the content pack you have downloaded ():
19. Enter 'yes' to the question:
    Do you wish to start the server now? (yes or no)

Please note that KAlite is not started automatically after boot; this must be added manually in the 'startup applications' of Ubuntu.

**Comment by benjaoming** [comment]
@JMNB 

Thanks for the feedback!

KA Lite is supposedly started at boot (unless there was a deviation in the 0.16 series) but this can be dependent on the choices of a previous installation where you might have made a different setting. 

Adding it to "Startup applications" is a valid choice, but it's dependent on whether the user is logged into the desktop, because that's when it triggers.

The alternative would be to run `sudo systemctl enable ka-lite` to make it start at boot.

Good luck with the deployments in Ethiopia, and always happy to help if you have further questions. Be sure to check out the deployments map, too, if you haven't already:

https://learningequality.org/ka-lite/map/
